### PR TITLE
fix #919

### LINKED ISSUE #919: Website doesn’t work in Firefox 60.8.0 ESR
I see just a blank page and the following error in the console:

```
TypeError: Object.fromEntries is not a function[Learn More]
```

### PR DESCRIPTION
**Pull request by jaeh**
replace Object.fromEntries with an entries function,
fixes #919 

this should reduce required firefox version down to 47 according to caniuse:
https://caniuse.com/#search=entries

### CODE REVIEW

**Comment by jorgebucaran** [comment]
This is great! Thank you, @jaeh! 🙌

**Comment by jirutka** [comment]
It doesn’t work, now I’m getting: `TypeError: r.forEach is not a function` in Firefox 60. And since you don’t even deploy source maps, I cannot provide more details without extra effort digging in minified code.

**Comment by jorgebucaran** [comment]
Would you like to help with this, @jirutka?
