### ISSUE TITLE
Website doesn’t work in Firefox 60.8.0 ESR

### ISSUE THREAD

**Issue by jirutka** [jorgebucaran/hyperapp#919]
I see just a blank page and the following error in the console:

```
TypeError: Object.fromEntries is not a function[Learn More]
```

**Comment by sergey-shpak** [comment]
@jorgebucaran, @loteoo  should we add 'babel/preset-env' configuration to define supported browser versions, like: `last 2 versions` or `> 5%` ?

**Comment by zaceno** [comment]
Since we're using parcel it should be enough to add e.g: `"browserslist": ">5%"` to the `package.json`

**Comment by jirutka** [comment]
It’s a presentational website, so `>5%` is too restrictive. Generally recommended query is something like:

```json
"browserslist": [
  ">0.5%",
  "Firefox ESR",
  "not dead"
]
```

You certainly shouldn’t go over 1 %.

**Comment by zaceno** [comment]
@jirutka right. I didn't mean to express any opinion on what browser to support or not. I was just copying from higher up in the thread. 

My point was really: thanks to parcel, it aught to be as easy as adding a browserslist field directly in the top level of package.json

**Comment by jirutka** [comment]
> Since we're using parcel it should be enough to add e.g: "browserslist": ">5%" to the package.json

It’s not, I just tried it. :/

**Comment by jirutka** [comment]
The problem is that `parcel-bundler 1.12.4` depends on `core-js ^2.6.5` that doesn’t support `Object.fromEntries` yet (it’s supported since 3.0.0). That’s a quite good example of why these “magic” all-in-one tools are better to avoid…

**Comment by selfup** [comment]
An alternative for the tuples can be quite short and not require polyfills:

```js
const state =  [ ['0', 'a'], ['1', 'b'], ['2', 'c'] ];

state.reduce((acc, values) => {
  const key = values[0] || null;
  const value = values[1] || null;

  acc[key] = value;
    
  return acc;
}, {});
```

A shorter version:

```js
const state =  [['0', 'a'], ['1', 'b'], ['2', 'c']];

state.reduce((a, v) => { a[v[0]] = v[1]; return a; }, {});
```

**Comment by jorgebucaran** [comment]
If the site is using `Object.fromEntries` anywhere, then let's just create an `entries()` utility function that does what we need.
